# Generated by Django 5.0.1 on 2024-02-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('Guide_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Guide_Name', models.CharField(max_length=50)),
                ('Guide_Lang', models.CharField(max_length=50)),
                ('Guide_Tel', models.CharField(max_length=10)),
                ('Guide_Mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('Responsible_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Responsible_Name', models.CharField(max_length=25)),
                ('Responsible_Pos', models.CharField(max_length=50)),
                ('Responsible_Tel', models.CharField(max_length=10)),
                ('Responsible_Mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('Visitor_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Visitor_Name', models.CharField(max_length=50)),
                ('Visitor_Mail', models.CharField(max_length=50)),
                ('Visitor_Tel', models.CharField(max_length=10)),
                ('Visitor_Card', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Ticket_Type', models.CharField(max_length=20)),
                ('Ticket_Date', models.DateField()),
                ('Ticket_Time', models.TimeField()),
                ('Ticket_Count', models.IntegerField()),
                ('Ticket_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ticket_Status', models.CharField(max_length=15)),
                ('Ticket_Guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbooking.guide')),
                ('Visitor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbooking.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Booking_Count', models.IntegerField()),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.TimeField()),
                ('Guide_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbooking.guide')),
                ('Responsible_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbooking.responsible')),
                ('Visitor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbooking.visitor')),
            ],
        ),
    ]
