# Generated by Django 5.0.1 on 2024-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
