# Generated by Django 5.0.1 on 2024-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbooking', '0002_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
