# Generated by Django 5.0.1 on 2024-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbooking', '0006_alter_visitor_visitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_Status',
            field=models.CharField(default='booked', max_length=15),
        ),
    ]
