# Generated by Django 5.0.1 on 2024-02-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soubenir',
            new_name='Souvenir',
        ),
    ]
