# Generated by Django 5.0.1 on 2024-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_date', models.DateField()),
                ('news_author', models.CharField(max_length=100)),
                ('news_category', models.CharField(max_length=100)),
                ('news_description', models.TextField()),
                ('news_image', models.ImageField(upload_to='news_images/')),
                ('news_status', models.CharField(max_length=20)),
            ],
        ),
    ]
