# Generated by Django 5.0.1 on 2024-02-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0002_remove_exhibit_id_alter_exhibit_exhibit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/exhibit_photos/'),
        ),
    ]
